name: Deploy via SCP

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Download theme artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: package-theme.yml
          name: culinarylab-theme-1.1.2
          path: ./artifacts/theme
          
      - name: Download plugin artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: package-plugin.yml
          name: recipe-plugin-1.1.2
          path: ./artifacts/plugin
      
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SFTP_KEY }}
          known_hosts: ${{ secrets.SFTP_KNOWN_HOSTS }}
          if_key_exists: fail
          
      - name: Deploy Theme via SCP
        run: |
          scp -r ./artifacts/theme/* ${{ secrets.SFTP_USERNAME }}@${{ secrets.SFTP_SERVER }}:${{ secrets.SERVER_BASEDIR }}themes/
          
      - name: Deploy Plugin via SCP
        run: |
          scp -r ./artifacts/plugin/* ${{ secrets.SFTP_USERNAME }}@${{ secrets.SFTP_SERVER }}:${{ secrets.SERVER_BASEDIR }}plugins/