name: Package Theme

on:
  push:
    branches: [ main ]
    paths:
      - 'masterchef/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Get theme version
        id: theme_version
        run: |
          VERSION=$(grep -m 1 "Version:" masterchef/style.css | awk -F': ' '{print $2}' | tr -d '\r')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Theme version detected: $VERSION"
      
      - name: Package theme
        run: |
          cd masterchef
          # Remove unnecessary development files
          rm -rf .git .github .gitignore .DS_Store
          # Create zip package
          zip -r ../culinarylab-${{ steps.theme_version.outputs.version }}.zip .
      
      - name: Upload theme package
        uses: actions/upload-artifact@v4
        with:
          name: culinarylab-theme-${{ steps.theme_version.outputs.version }}
          path: culinarylab-${{ steps.theme_version.outputs.version }}.zip
          retention-days: 90
      
      - name: Create Release
        if: github.event_name != 'pull_request'
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: theme-v${{ steps.theme_version.outputs.version }}
          name: CulinaryLab Theme v${{ steps.theme_version.outputs.version }}
          draft: false
          prerelease: false
          files: culinarylab-${{ steps.theme_version.outputs.version }}.zip