name: Package Plugin

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Get plugin version
        id: plugin_version
        run: |
          VERSION=$(grep -m 1 " \* Version:" recipe-plugin/recipe-plugin.php | awk -F': ' '{print $2}' | tr -d '\r')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Plugin version detected: $VERSION"
      
      - name: Package plugin
        run: |
          cd recipe-plugin
          # Remove unnecessary development files
          rm -rf .git .github .gitignore .DS_Store
          # Create zip package
          zip -r ../recipe-plugin-${{ steps.plugin_version.outputs.version }}.zip .
      
      - name: Upload plugin package
        uses: actions/upload-artifact@v4
        with:
          name: recipe-plugin-${{ steps.plugin_version.outputs.version }}
          path: recipe-plugin-${{ steps.plugin_version.outputs.version }}.zip
          retention-days: 90
      
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: Recipe Plugin v${{ steps.plugin_version.outputs.version }}
          draft: false
          prerelease: false
          files: recipe-plugin-${{ steps.plugin_version.outputs.version }}.zip